# Dependencies
markdown:         kramdown
rouge:            true

# Permalinks
permalink:        pretty

# Setup
title:            D13d3l.nl
tagline:          "SDiedel's personal blogging space"
description:      ''
url:              http://lanyon.getpoole.com

author:
  name:           'SDiedel'
  url:            https://twitter.com/sdiedel

paginate:         10

# Custom vars
version:          1.0.0

twitter_username:     sdiedel
github_username:      sdiedel
linkedin_username:    stefandiedel

github:
  repo:           https://github.com/poole/lanyon
